### ISSUE TITLE
Improve documentation (episode 1)

### ISSUE THREAD

**Issue by benjaminbollen** [OpenST/JLP#80]
- [ ] UBT, improve documentation L102, L133, L134, L168
- [ ] Improve variable names for fee amount, gatewayBase L461
- [x] rename `messageStatus` to `inboxMessageStatus` L245 (also change other methods)
- [x] OSTPrime, use "base coin" for base token and "OST" for token L58
- [x] fix comment in message bus L245 "inbox on target"
- [x] make comments in GatewayBase more general, don't use Stake/Mint terms (L73)
- [x] in GatewayComposer, document function to explain why mint recalculated
- [x] in JLP readme, add that deployed anchors is a pre-requisite for UBT setup
